server:
   port: 8080
   contextPath: /BCT
environment: development
spring:
   profiles:
      active: dev
   datasource:
      url: jdbc:oracle:thin:@bctrac5:1522:dbdev11
      username: db_gosdmx
      password: db_gosdmx_dev
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: oracle.jdbc.OracleDriver
      initialize: true
   jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
         ddl-auto: create-drop
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
         hibernate:
            enable_lazy_load_no_trans: true
            format_sql: true
            dialect: org.hibernate.dialect.Oracle12cDialect
   spring:
      thymeleaf:
         mode: LEGACYHTML5
         cache: false
---
environment: test
spring:
   profiles: test
   datasource:
      url: jdbc:oracle:thin:@bctrac5:1522:dbdev11
      username: db_gosdmx
      password: db_gosdmx_dev
      testWhileIdle: true
      validationQuery: SELECT 1
      driverClassName: oracle.jdbc.OracleDriver
      initialize: true
   jpa:
      show-sql: false
      generate-ddl: true
      hibernate:
         ddl-auto: none
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
         hibernate:
            enable_lazy_load_no_trans: true
            format_sql: true
            dialect: org.hibernate.dialect.Oracle12cDialect
   spring:
      thymeleaf:
         mode: LEGACYHTML5
         cache: false